"""
I-ViT Architecture Surgery for HuggingFace MobileViT
=====================================================

Phase 1: Dynamically replace FP32 Transformer sub-modules inside
HuggingFace's `MobileViTTransformerLayer` with I-ViT integer-only
equivalents (QuantLinear, IntLayerNorm, IntSoftmax / Shiftmax,
IntGELU / ShiftGELU) while preserving pre-trained weights.

The CNN stem (MobileNetV2 inverted residuals) is left UNTOUCHED.

Key design decisions:
  - The I-ViT framework passes `(tensor, act_scaling_factor)` tuples
    through every layer.  HuggingFace's MobileViT expects plain tensors.
    We bridge this mismatch by initialising the quantisation context
    (QuantAct) at the entrance of each replacement block and stripping
    the scaling factor at the exit so that the surrounding CNN code
    never sees the extra return value.
  - Weight mapping is done by name; see `build_weight_map()` for the
    full correspondence table.

Author : Capstone Team (auto-generated by Antigravity)
"""

# --- Apply device-compatibility patches BEFORE importing I-ViT modules ---
# This must come first to monkey-patch hardcoded .cuda() calls in I-ViT.
import sys, os
IVIT_ROOT = os.environ.get("IVIT_ROOT")
if not IVIT_ROOT or not os.path.exists(IVIT_ROOT):
    cand_rel = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "I-ViT"))
    if os.path.exists(cand_rel):
        IVIT_ROOT = cand_rel
    else:
        for cand in ["/content/I-ViT", os.path.abspath("I-ViT"), os.path.abspath("../I-ViT"), os.path.expanduser("~/I-ViT")]:
            if os.path.exists(cand):
                IVIT_ROOT = cand
                break
        else:
            IVIT_ROOT = cand_rel

if IVIT_ROOT and IVIT_ROOT not in sys.path:
    sys.path.insert(0, IVIT_ROOT)

# Add the surgery package to sys.path for the patch import
_SURGERY_DIR = os.path.dirname(os.path.abspath(__file__))
_NOTEBOOK_DIR = os.path.dirname(_SURGERY_DIR)
if _NOTEBOOK_DIR not in sys.path:
    sys.path.insert(0, _NOTEBOOK_DIR)

from ivit_surgery import patch_ivit_device  # noqa: F401  — applies monkey-patches

import copy, math
from functools import partial
from collections import OrderedDict

import torch
import torch.nn as nn
import torch.nn.functional as F

# I-ViT quantisation primitives are already importable thanks to the
# sys.path setup at the top of this file.
from models.quantization_utils import (
    QuantLinear,
    QuantAct,
    QuantMatMul,
    IntLayerNorm,
    IntSoftmax,   # Shiftmax
    IntGELU,      # ShiftGELU
)


# ===================================================================
# 1. Integer-only Self-Attention (replaces MobileViTSelfAttention)
# ===================================================================

class IViTSelfAttention(nn.Module):
    """
    Integer-only self-attention that mirrors HuggingFace's
    `MobileViTSelfAttention` but uses I-ViT primitives.

    HF layout (separate Q / K / V projections, each `hidden_size -> hidden_size`):
        query  = nn.Linear(hidden_size, all_head_size)
        key    = nn.Linear(hidden_size, all_head_size)
        value  = nn.Linear(hidden_size, all_head_size)

    I-ViT layout (fused QKV, `hidden_size -> 3 * hidden_size`):
        qkv = QuantLinear(hidden_size, 3 * hidden_size)

    During weight transfer we *fuse* the three HF weight matrices into
    the single QKV weight matrix expected by I-ViT.
    """

    def __init__(self, hidden_size: int, num_attention_heads: int,
                 attn_drop: float = 0.0, qkv_bias: bool = True):
        super().__init__()
        self.num_attention_heads = num_attention_heads
        self.attention_head_size = hidden_size // num_attention_heads
        self.all_head_size = num_attention_heads * self.attention_head_size
        self.scale = self.attention_head_size ** -0.5

        # ---------- I-ViT quantised layers ----------
        self.qkv = QuantLinear(hidden_size, hidden_size * 3, bias=qkv_bias)
        self.qact1 = QuantAct()            # after QKV projection
        self.qact_attn1 = QuantAct()       # after Q·K^T scaling
        self.int_softmax = IntSoftmax(16)  # Shiftmax (16-bit accumulation)
        self.qact_softmax = QuantAct()     # (kept for future calibration hooks)
        self.qact2 = QuantAct()            # after context reshape
        self.proj = QuantLinear(hidden_size, hidden_size, bias=True)
        self.qact3 = QuantAct(16)          # output quantisation

        self.matmul_1 = QuantMatMul()      # Q · K^T
        self.matmul_2 = QuantMatMul()      # attn · V

        self.attn_drop = nn.Dropout(attn_drop)

    # ---- forward bridges I-ViT tuple protocol ----
    def forward(self, x: torch.Tensor, act_scaling_factor: torch.Tensor):
        B, N, C = x.shape

        # QKV projection (fused)
        x, act_scaling_factor = self.qkv(x, act_scaling_factor)
        x, act_scaling_factor_1 = self.qact1(x, act_scaling_factor)

        qkv = x.reshape(B, N, 3, self.num_attention_heads,
                         C // self.num_attention_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]

        # Attention scores  (Q · K^T) / sqrt(d)
        attn, act_scaling_factor = self.matmul_1(
            q, act_scaling_factor_1,
            k.transpose(-2, -1), act_scaling_factor_1)
        attn = attn * self.scale
        act_scaling_factor = act_scaling_factor * self.scale
        attn, act_scaling_factor = self.qact_attn1(attn, act_scaling_factor)

        # Shiftmax (integer softmax)
        attn, act_scaling_factor = self.int_softmax(attn, act_scaling_factor)
        attn = self.attn_drop(attn)

        # Context  (attn · V)
        x, act_scaling_factor = self.matmul_2(
            attn, act_scaling_factor,
            v, act_scaling_factor_1)
        x = x.transpose(1, 2).reshape(B, N, C)

        # Output projection
        x, act_scaling_factor = self.qact2(x, act_scaling_factor)
        x, act_scaling_factor = self.proj(x, act_scaling_factor)
        x, act_scaling_factor = self.qact3(x, act_scaling_factor)

        return x, act_scaling_factor


# ===================================================================
# 2. Integer-only MLP (replaces MobileViTIntermediate + MobileViTOutput)
# ===================================================================

class IViTMlp(nn.Module):
    """
    Two-layer MLP with ShiftGELU activation, mirroring the combined
    effect of HF's `MobileViTIntermediate` (fc1 + act) and
    `MobileViTOutput` (fc2 + dropout + residual-add).

    NOTE: The residual addition is handled *outside* this module
    (in the parent IViTMobileViTTransformerLayer) to match HF's
    data-flow exactly.
    """

    def __init__(self, hidden_size: int, intermediate_size: int,
                 drop: float = 0.0):
        super().__init__()
        # fc1: hidden -> intermediate   (was MobileViTIntermediate.dense)
        self.fc1 = QuantLinear(hidden_size, intermediate_size)
        self.act = IntGELU()       # ShiftGELU
        self.qact_gelu = QuantAct()
        self.qact1 = QuantAct()

        # fc2: intermediate -> hidden   (was MobileViTOutput.dense)
        self.fc2 = QuantLinear(intermediate_size, hidden_size)
        self.qact2 = QuantAct(16)

        self.drop = nn.Dropout(drop)

    def forward(self, x: torch.Tensor, act_scaling_factor: torch.Tensor):
        x, act_scaling_factor = self.fc1(x, act_scaling_factor)
        x, act_scaling_factor = self.qact_gelu(x, act_scaling_factor)
        x, act_scaling_factor = self.act(x, act_scaling_factor)
        x, act_scaling_factor = self.qact1(x, act_scaling_factor)
        x = self.drop(x)
        x, act_scaling_factor = self.fc2(x, act_scaling_factor)
        x, act_scaling_factor = self.qact2(x, act_scaling_factor)
        x = self.drop(x)
        return x, act_scaling_factor


# ===================================================================
# 3. Full Replacement Block  (replaces MobileViTTransformerLayer)
# ===================================================================

class IViTMobileViTTransformerLayer(nn.Module):
    """
    Drop-in replacement for HuggingFace's `MobileViTTransformerLayer`.

    Structure comparison:
    ┌──────────────────────────────────────────────┐
    │  HF (FP32)                │  I-ViT (INT)     │
    ├──────────────────────────────────────────────┤
    │  layernorm_before (LN)    │  norm1 (IntLN)   │
    │  attention (SA + proj)    │  attn (IViTSA)   │
    │  residual add             │  qact_res1       │
    │  layernorm_after  (LN)    │  norm2 (IntLN)   │
    │  intermediate (fc1+act)   │  mlp  (IViTMlp)  │
    │  output (fc2+drop+resid)  │  qact_res2       │
    └──────────────────────────────────────────────┘

    The forward() signature accepts and returns a *plain tensor* (no
    scaling-factor tuple) so the surrounding MobileViTTransformer loop
    does not need to change.  We create and consume the QuantAct
    context internally.
    """

    def __init__(self, hidden_size: int, intermediate_size: int,
                 num_attention_heads: int,
                 attn_drop: float = 0.0,
                 hidden_drop: float = 0.0,
                 qkv_bias: bool = True,
                 layer_norm_eps: float = 1e-5):
        super().__init__()

        # --- Integer LayerNorms ---
        self.norm1 = IntLayerNorm(hidden_size, eps=layer_norm_eps)
        self.norm2 = IntLayerNorm(hidden_size, eps=layer_norm_eps)

        # --- Entry / exit quantisation ---
        self.qact_input = QuantAct()    # bootstrap scaling factor from raw FP tensor
        self.qact1 = QuantAct()         # after norm1
        self.qact_res1 = QuantAct(16)   # residual-add after attention
        self.qact3 = QuantAct()         # after norm2
        self.qact_res2 = QuantAct(16)   # residual-add after MLP

        # --- Core blocks ---
        self.attn = IViTSelfAttention(
            hidden_size=hidden_size,
            num_attention_heads=num_attention_heads,
            attn_drop=attn_drop,
            qkv_bias=qkv_bias,
        )

        self.mlp = IViTMlp(
            hidden_size=hidden_size,
            intermediate_size=intermediate_size,
            drop=hidden_drop,
        )

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        """
        Accepts a plain tensor (B*P, N, C) from the HF pipeline,
        runs everything through I-ViT quantised blocks, and returns
        a plain tensor.
        """
        # --- Bootstrap quantisation context ---
        x_1, act_scaling_factor_1 = self.qact_input(hidden_states)

        # --- Pre-norm + Self-Attention ---
        x, act_scaling_factor = self.norm1(x_1, act_scaling_factor_1)
        x, act_scaling_factor = self.qact1(x, act_scaling_factor)
        x, act_scaling_factor = self.attn(x, act_scaling_factor)

        # --- Residual add (attention output + input) ---
        x_2, act_scaling_factor_2 = self.qact_res1(
            x, act_scaling_factor, x_1, act_scaling_factor_1)

        # --- Pre-norm + MLP ---
        x, act_scaling_factor = self.norm2(x_2, act_scaling_factor_2)
        x, act_scaling_factor = self.qact3(x, act_scaling_factor)
        x, act_scaling_factor = self.mlp(x, act_scaling_factor)

        # --- Residual add (MLP output + attention-residual) ---
        x, act_scaling_factor = self.qact_res2(
            x, act_scaling_factor, x_2, act_scaling_factor_2)

        # Strip the quantisation context -> plain tensor for HF pipeline
        return x


# Alias matching requirement name (IViTMobileViTEncoderLayer)
IViTMobileViTEncoderLayer = IViTMobileViTTransformerLayer


# ===================================================================
# 4. Weight-Transfer Utilities
# ===================================================================

def build_weight_map(old_prefix: str, new_prefix: str) -> dict:
    """
    Build the state-dict key mapping from a single HF
    `MobileViTTransformerLayer` to an `IViTMobileViTTransformerLayer`.

    Parameters
    ----------
    old_prefix : str
        The dotted prefix in the *original* model's state_dict that
        points to one MobileViTTransformerLayer, e.g.
        ``"mobilevit.encoder.layer.2.transformer.layer.0"``.
    new_prefix : str
        The corresponding prefix in the *surgered* model (usually
        identical to old_prefix after in-place replacement).

    Returns
    -------
    dict  {old_key: new_key}

    Key Mapping Table
    -----------------
    HF Original Key                          →  I-ViT Replacement Key
    ──────────────────────────────────────────────────────────────────
    # LayerNorms
    layernorm_before.weight                  →  norm1.weight
    layernorm_before.bias                    →  norm1.bias
    layernorm_after.weight                   →  norm2.weight
    layernorm_after.bias                     →  norm2.bias

    # Self-Attention Q/K/V → fused QKV
    #   HF has separate query / key / value  (each hidden_size × hidden_size)
    #   I-ViT fuses them into one            (hidden_size × 3·hidden_size)
    #   → these are handled specially via `fuse_qkv_weights()`, NOT via
    #     simple key rename.  The map below lists them for documentation
    #     purposes; the actual transfer is done programmatically.
    attention.attention.query.weight         →  attn.qkv.weight  (rows 0:H)
    attention.attention.query.bias           →  attn.qkv.bias    (rows 0:H)
    attention.attention.key.weight           →  attn.qkv.weight  (rows H:2H)
    attention.attention.key.bias             →  attn.qkv.bias    (rows H:2H)
    attention.attention.value.weight         →  attn.qkv.weight  (rows 2H:3H)
    attention.attention.value.bias           →  attn.qkv.bias    (rows 2H:3H)

    # Self-Attention output projection
    attention.output.dense.weight            →  attn.proj.weight
    attention.output.dense.bias              →  attn.proj.bias

    # MLP  fc1  (was MobileViTIntermediate.dense)
    intermediate.dense.weight                →  mlp.fc1.weight
    intermediate.dense.bias                  →  mlp.fc1.bias

    # MLP  fc2  (was MobileViTOutput.dense)
    output.dense.weight                      →  mlp.fc2.weight
    output.dense.bias                        →  mlp.fc2.bias
    """

    # Simple 1-to-1 renames (everything except QKV which needs fusing)
    mapping = {
        # LayerNorms
        f"{old_prefix}.layernorm_before.weight": f"{new_prefix}.norm1.weight",
        f"{old_prefix}.layernorm_before.bias":   f"{new_prefix}.norm1.bias",
        f"{old_prefix}.layernorm_after.weight":  f"{new_prefix}.norm2.weight",
        f"{old_prefix}.layernorm_after.bias":    f"{new_prefix}.norm2.bias",

        # Attention output projection
        f"{old_prefix}.attention.output.dense.weight": f"{new_prefix}.attn.proj.weight",
        f"{old_prefix}.attention.output.dense.bias":   f"{new_prefix}.attn.proj.bias",

        # MLP fc1  (Intermediate)
        f"{old_prefix}.intermediate.dense.weight": f"{new_prefix}.mlp.fc1.weight",
        f"{old_prefix}.intermediate.dense.bias":   f"{new_prefix}.mlp.fc1.bias",

        # MLP fc2  (Output)
        f"{old_prefix}.output.dense.weight": f"{new_prefix}.mlp.fc2.weight",
        f"{old_prefix}.output.dense.bias":   f"{new_prefix}.mlp.fc2.bias",
    }
    return mapping


def fuse_qkv_weights(old_state: dict, old_prefix: str,
                     new_state: dict, new_prefix: str):
    """
    Fuse three separate Q / K / V weight matrices from HuggingFace's
    `MobileViTSelfAttention` into the single concatenated QKV matrix
    expected by I-ViT's `QuantLinear(dim, 3*dim)`.

    Layout in the fused tensor (dim=H):
        qkv.weight = [ Q.weight ]   rows  0 : H
                     [ K.weight ]   rows  H : 2H
                     [ V.weight ]   rows 2H : 3H
    Same for bias.
    """
    q_w = old_state[f"{old_prefix}.attention.attention.query.weight"]
    k_w = old_state[f"{old_prefix}.attention.attention.key.weight"]
    v_w = old_state[f"{old_prefix}.attention.attention.value.weight"]

    new_state[f"{new_prefix}.attn.qkv.weight"] = torch.cat([q_w, k_w, v_w], dim=0)

    q_b_key = f"{old_prefix}.attention.attention.query.bias"
    k_b_key = f"{old_prefix}.attention.attention.key.bias"
    v_b_key = f"{old_prefix}.attention.attention.value.bias"

    if q_b_key in old_state:
        q_b = old_state[q_b_key]
        k_b = old_state[k_b_key]
        v_b = old_state[v_b_key]
        new_state[f"{new_prefix}.attn.qkv.bias"] = torch.cat([q_b, k_b, v_b], dim=0)


def transfer_weights(old_model_state: dict,
                     new_model: nn.Module,
                     layer_prefixes: list):
    """
    Transfer ALL pre-trained weights from the original FP32 model to
    the surgered I-ViT model.

    Parameters
    ----------
    old_model_state : dict
        `original_model.state_dict()` (before surgery).
    new_model : nn.Module
        The model **after** block replacement.
    layer_prefixes : list of str
        Dotted prefixes for each MobileViTTransformerLayer that was
        replaced, e.g.:
          ["mobilevit.encoder.layer.2.transformer.layer.0",
           "mobilevit.encoder.layer.2.transformer.layer.1", ...]

    Returns
    -------
    new_model with weights loaded (in-place).
    """
    new_state = new_model.state_dict()

    # ------------------------------------------------------------------
    # Step 1: Copy all NON-transformer keys verbatim
    #         (CNN stem, final classifier, etc.)
    # ------------------------------------------------------------------
    transformer_key_prefixes = set()
    for pfx in layer_prefixes:
        transformer_key_prefixes.add(pfx)

    for key, value in old_model_state.items():
        # Skip keys that belong to a replaced transformer layer
        belongs_to_replaced = False
        for pfx in transformer_key_prefixes:
            if key.startswith(pfx + "."):
                belongs_to_replaced = True
                break
        if not belongs_to_replaced and key in new_state:
            new_state[key] = value

    # ------------------------------------------------------------------
    # Step 2: Transfer transformer-block weights with key remapping
    # ------------------------------------------------------------------
    for pfx in layer_prefixes:
        # 2a. Simple 1:1 renamed keys
        weight_map = build_weight_map(pfx, pfx)
        for old_key, new_key in weight_map.items():
            if old_key in old_model_state and new_key in new_state:
                new_state[new_key] = old_model_state[old_key]
            else:
                print(f"  [WARN] missing key pair: {old_key} -> {new_key}")

        # 2b. Fused QKV
        fuse_qkv_weights(old_model_state, pfx, new_state, pfx)

    # ------------------------------------------------------------------
    # Step 3: Load the assembled state dict (strict=False because I-ViT
    #         adds buffers like fc_scaling_factor that have no counterpart
    #         in the original model).
    # ------------------------------------------------------------------
    missing, unexpected = new_model.load_state_dict(new_state, strict=False)

    # Filter noise: quantisation buffers are expected to be "missing"
    # from the old model — they will be initialised on the first forward.
    real_missing = [k for k in missing
                    if not any(tok in k for tok in
                               ("scaling_factor", "weight_integer",
                                "bias_integer", "min_val", "max_val",
                                "act_scaling_factor", "norm_scaling_factor"))]
    if real_missing:
        print(f"  [WARN] Truly missing keys after weight transfer:\n    "
              + "\n    ".join(real_missing))

    return new_model


# ===================================================================
# 5. Graph-Injection Function
# ===================================================================

def find_transformer_layer_paths(model: nn.Module) -> list:
    """
    Walk the model graph and return dotted-path prefixes for every
    `MobileViTTransformerLayer` instance.
    """
    from transformers.models.mobilevit.modeling_mobilevit import (
        MobileViTTransformerLayer,
    )
    paths = []
    for name, module in model.named_modules():
        if isinstance(module, MobileViTTransformerLayer):
            paths.append(name)
    return paths


def _set_module_by_name(model: nn.Module, dotted_name: str, new_module: nn.Module):
    """Utility: set `model.<dotted_name> = new_module` using recursive getattr."""
    parts = dotted_name.split(".")
    parent = model
    for p in parts[:-1]:
        parent = getattr(parent, p)
    setattr(parent, parts[-1], new_module)


def replace_mobilevit_blocks(model: nn.Module,
                             num_attention_heads: int = 4,
                             mlp_ratio: float = 2.0,
                             qkv_bias: bool = True,
                             attn_drop: float = 0.0,
                             hidden_drop: float = 0.0,
                             layer_norm_eps: float = 1e-5) -> nn.Module:
    """
    Traverse `model.named_modules()`, identify every HuggingFace
    `MobileViTTransformerLayer`, and replace it in-place with an
    `IViTMobileViTTransformerLayer` that uses I-ViT integer-only
    primitives.

    Parameters
    ----------
    model : nn.Module
        A HuggingFace `MobileViTForImageClassification` (or any model
        containing `MobileViTTransformerLayer` instances).
    num_attention_heads : int
        Number of attention heads (default 4 for mobilevit-xx-small).
    mlp_ratio : float
        Expansion ratio for the MLP intermediate size (default 2.0).
    qkv_bias : bool
        Whether the QKV projection includes bias (default True).

    Returns
    -------
    model : nn.Module
        The same model object with transformer layers swapped.
    replaced_prefixes : list of str
        Dotted paths of the replaced layers (needed by `transfer_weights`).
    """
    from transformers.models.mobilevit.modeling_mobilevit import (
        MobileViTTransformerLayer,
    )

    # --- Snapshot the original state dict BEFORE any replacement ---
    original_state = copy.deepcopy(model.state_dict())

    replaced_prefixes = []

    for name, module in list(model.named_modules()):
        if not isinstance(module, MobileViTTransformerLayer):
            continue

        # Infer hidden_size from the existing LayerNorm
        hidden_size = module.layernorm_before.normalized_shape[0]
        intermediate_size = int(hidden_size * mlp_ratio)

        # Build the replacement
        new_layer = IViTMobileViTTransformerLayer(
            hidden_size=hidden_size,
            intermediate_size=intermediate_size,
            num_attention_heads=num_attention_heads,
            attn_drop=attn_drop,
            hidden_drop=hidden_drop,
            qkv_bias=qkv_bias,
            layer_norm_eps=layer_norm_eps,
        )

        # Swap it into the model graph
        _set_module_by_name(model, name, new_layer)
        replaced_prefixes.append(name)
        print(f"  [SURGERY] Replaced: {name}  "
              f"(hidden={hidden_size}, inter={intermediate_size})")

    # --- Transfer pre-trained weights ---
    model = transfer_weights(original_state, model, replaced_prefixes)

    return model, replaced_prefixes


# ===================================================================
# 6. Main — Validation Test (Dummy Forward Pass)
# ===================================================================

def main():
    """
    Load the base `apple/mobilevit-xx-small` model, apply the I-ViT
    architecture surgery, and validate with a dummy forward pass.
    """
    from transformers import MobileViTForImageClassification

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n{'='*60}")
    print("  I-ViT Architecture Surgery — Phase 1 Validation")
    print(f"  Device: {device}")
    print(f"{'='*60}\n")

    # ------------------------------------------------------------------
    # A. Load original pre-trained model
    # ------------------------------------------------------------------
    print("[1/4] Loading original apple/mobilevit-xx-small ...")
    original_model = MobileViTForImageClassification.from_pretrained(
        "apple/mobilevit-xx-small", low_cpu_mem_usage=True
    )
    original_model.eval().to(device)

    # ------------------------------------------------------------------
    # B. Create a deep copy and apply surgery
    # ------------------------------------------------------------------
    print("\n[2/4] Cloning model and performing I-ViT surgery ...")
    surgered_model = copy.deepcopy(original_model)
    surgered_model, replaced = replace_mobilevit_blocks(
        surgered_model,
        num_attention_heads=4,   # from mobilevit-xx-small config
        mlp_ratio=2.0,           # from mobilevit-xx-small config
        qkv_bias=True,
        attn_drop=0.0,
        hidden_drop=0.05,        # hidden_dropout_prob in config
        layer_norm_eps=1e-5,
    )
    surgered_model.eval().to(device)

    print(f"\n  Total transformer layers replaced: {len(replaced)}")
    for r in replaced:
        print(f"    * {r}")

    # ------------------------------------------------------------------
    # C. Dummy forward pass
    # ------------------------------------------------------------------
    print("\n[3/4] Running dummy forward pass  [1, 3, 256, 256] ...")
    dummy_input = torch.randn(1, 3, 256, 256, device=device)

    with torch.no_grad():
        out_original = original_model(pixel_values=dummy_input).logits
        out_surgered = surgered_model(pixel_values=dummy_input).logits

    print(f"  Original output shape : {out_original.shape}")
    print(f"  Surgered output shape : {out_surgered.shape}")

    # ------------------------------------------------------------------
    # D. MSE comparison
    # ------------------------------------------------------------------
    mse = F.mse_loss(out_original, out_surgered).item()
    cosine_sim = F.cosine_similarity(
        out_original.view(1, -1), out_surgered.view(1, -1)
    ).item()

    print(f"\n[4/4] Comparison metrics:")
    print(f"  MSE between logits           : {mse:.6f}")
    print(f"  Cosine similarity of logits  : {cosine_sim:.6f}")
    print(f"\n  NOTE: MSE != 0 is expected due to Shiftmax / ShiftGELU / fake-")
    print(f"        quantisation initialisations.  What matters is that the")
    print(f"        forward pass completes without shape mismatches.\n")

    # ------------------------------------------------------------------
    # E. Quick sanity: both predict the same top-5
    # ------------------------------------------------------------------
    topk_orig = out_original.topk(5).indices[0].tolist()
    topk_surg = out_surgered.topk(5).indices[0].tolist()
    overlap = len(set(topk_orig) & set(topk_surg))
    print(f"  Top-5 class overlap: {overlap}/5")
    print(f"    Original : {topk_orig}")
    print(f"    Surgered : {topk_surg}")
    print(f"\n{'='*60}")
    print("  Phase 1 Surgery -- COMPLETE [OK]")
    print(f"{'='*60}\n")

    return original_model, surgered_model


if __name__ == "__main__":
    main()
